### ISSUE TITLE
Part I - general comments

### ISSUE THREAD

**Issue by MartinBernard** [hres/pmp#29]
(1) There are some headers that were not available in the box-down box.  Is there a way to have free text? Once you start using the paragraphs with headers in part 1 you cannot go back to adding paragraphs without headers.

For example, under Part I - Warnings and Precautions adding a header called "other" which allows users to manually insert their sub section headers

(2) Part I - Drug Interactions : the drop menu is different than the Warning and Precautions drop list. Please make sure this is consistent across application.

**Comment by maadarani** [comment]
What do you mean by this "Once you start using the paragraphs with headers in part 1 you cannot go back to adding paragraphs without headers." ?

**Comment by maadarani** [comment]
2) This is because the requirement was to be able to add custom text in the drop menu. i.e. controlled vocabulary and ability to add your own. To do so, we need to it purely in HTML5 and not the traditional way, which means no down arrow. The traditional way with down arrow does not allow you to add your own text.

**Comment by MartinBernard** [comment]
re 1) - what i was trying to say is that for "Warnings and Precautions" section where there is drop menu, sub headings found there are not all encompassing, we should have the ability to also manually insert sub headings.

re 2) - Understood.

**Comment by maadarani** [comment]
Now you can add any text to the header
